export enum PageKeys {
  about = 'about',
  catalog = 'catalog',
  catalogSearch = 'catalog-search',
  catalogWrapper = 'catalog-wrapper',
  contacts = 'contacts',
  contactUs = 'contact-us',
  error = 'error',
  main = 'main',
  privacyPolicy = 'privacy-policy',
  product = 'product',
  productsList = 'products-list',
  services = 'services',
  subCategory = 'sub-category',
}
